name: Build and Deploy iOS for Multiple Unity Versions

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        description: "Unity license of the account to use"
        required: true

      UNITY_EMAIL:
        description: "Unity email of the account to use"
        required: true

      UNITY_PASSWORD:
        description: "Unity password of the account to use"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE:
        description: "Base64-encoded Apple Distribution Certificate (.p12)"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD:
        description: "Password for the Apple Distribution Certificate"
        required: true

      IOS_DISTRIBUTION_PROVISIONING_PROFILE:
        description: "Base64-encoded Provisioning Profile (.mobileprovision)"
        required: true

      KEYCHAIN_NAME:
        description: "Name of the keychain where the Certificate will be imported"
        required: true

      KEYCHAIN_PASSWORD:
        description: "Password for the keychain where the Certificate will be imported"
        required: true

      APP_STORE_AUTH_KEY:
        description: "Base64-Encoded App Store Auth Key (.p8)"
        required: true

      APP_STORE_ISSUER_ID:
        description: "App Store Auth Key Issuer ID"
        required: true

      APP_STORE_KEY_ID:
        description: "App Store Auth Key ID"
        required: true

jobs:
  ios-unity-build:
    strategy:
      matrix:
        unity_version:
          - "6000.0.40f1"
          - "2022.3.59f1"
          - "2021.3.45f1"
          - "2020.3.48f1"

    name: Unity ${{ matrix.unity_version }}
    uses: ./.github/workflows/unity-build.yml
    with:
      runner_image: ubuntu-latest
      target_platform: iOS
      unity_version: ${{ matrix.unity_version }}
      output_path: ./build/iOS/iOS/

    secrets:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  ios-xcode-build:
    needs: ios-unity-build
    strategy:
      matrix:
        unity_version:
          - "6000.0.40f1"
          - "2022.3.59f1"
          - "2021.3.45f1"
          - "2020.3.48f1"

    name: Xcode for ${{ matrix.unity_version }}
    uses: ./.github/workflows/xcode-ios.yml
    with:
      unity_version: ${{ matrix.unity_version }}
      artifact_name: "iOS_${{ matrix.unity_version }}_BuildOutput"

    secrets:
      APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      IOS_DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.IOS_DISTRIBUTION_PROVISIONING_PROFILE }}
      KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APP_STORE_AUTH_KEY: ${{ secrets.APP_STORE_AUTH_KEY }}
      APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
      APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
