on:
  workflow_call:
    inputs:
      unity_version:
        description: "Unity version used for the build"
        required: true
        type: string

      artifact_name:
        description: "Name of the artifact containing the Unity build"
        required: true
        type: string

    secrets:
      UNITY_LICENSE:
        description: "Unity license of the account to use"
        required: true

      UNITY_EMAIL:
        description: "Unity email of the account to use"
        required: true

      UNITY_PASSWORD:
        description: "Unity password of the account to use"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE:
        description: "Base64-encoded Apple Distribution Certificate (.p12)"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD:
        description: "Password for the Apple Distribution Certificate"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE_NAME:
        description: "Name for the Apple Distribution Certificate"
        required: true

      DISTRIBUTION_PROVISIONING_PROFILE:
        description: "Base64-encoded Provisioning Profile (.mobileprovision)"
        required: true

      KEYCHAIN_NAME:
        description: "Name of the keychain where the Certificate will be imported"
        required: true

      KEYCHAIN_PASSWORD:
        description: "Password for the keychain where the Certificate will be imported"
        required: true

      APP_STORE_AUTH_KEY:
        description: "Base64-Encoded App Store Auth Key (.p8)"
        required: true

      APP_STORE_ISSUER_ID:
        description: "App Store Auth Key Issuer ID"
        required: true

      APP_STORE_KEY_ID:
        description: "App Store Auth Key ID"
        required: true

jobs:
  ios-unity-build:
    uses: ./.github/workflows/unity-build.yml
    with:
      unity_version: ${{ inputs.unity_version }}
      artifact_name: ${{ inputs.artifact_name }}
      runner_image: ubuntu-latest
      target_platform: iOS
      output_path: ./build/iOS/iOS/

    secrets:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  ios-xcode-build:
    needs: ios-unity-build
    uses: ./.github/workflows/xcode-ios.yml
    with:
      unity_version: ${{ inputs.unity_version }}
      artifact_name: ${{ inputs.artifact_name }}
      target_platform: iOS

    secrets:
      APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      APPLE_DISTRIBUTION_CERTIFICATE_NAME: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_NAME }}
      DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.DISTRIBUTION_PROVISIONING_PROFILE }}
      KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APP_STORE_AUTH_KEY: ${{ secrets.APP_STORE_AUTH_KEY }}
      APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
      APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
