on:
  workflow_call:
    inputs:
      unity_version:
          description: "Unity version used for the build"
          required: true
          type: string

    secrets:
      UNITY_LICENSE:
          description: "Unity license of the account to use"
          required: true

      UNITY_EMAIL:
          description: "Unity email of the account to use"
          required: true

      UNITY_PASSWORD:
          description: "Unity password of the account to use"
          required: true
  
jobs:
  macos-unity-build:
    uses: ./.github/workflows/unity-build.yml
    with:
      unity_version: ${{ inputs.unity_version }}
      runner_image: macos-latest
      target_platform: StandaloneOSX
      output_path: ./build/StandaloneOSX/

    secrets:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  macos-codesign-and-upload:
    needs: macos-unity-build
    uses: ./.github/workflows/fastlane-build.yml
    with:
      unity_version: ${{ inputs.unity_version }}
      artifact_name: ${{ needs.macos-unity-build.outputs.artifact_name }}
      fastlane_platform: mac

    secrets:
      KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
      APPLE_DISTRIBUTION_CERTIFICATE_NAME: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_NAME }}
      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      INSTALLER_DISTRIBUTION_CERTIFICATE: ${{ secrets.INSTALLER_DISTRIBUTION_CERTIFICATE }}
      INSTALLER_DISTRIBUTION_CERTIFICATE_NAME: ${{ secrets.INSTALLER_DISTRIBUTION_CERTIFICATE_NAME }}
      INSTALLER_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.INSTALLER_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.DISTRIBUTION_PROVISIONING_PROFILE }}
      APP_STORE_AUTH_KEY: ${{ secrets.APP_STORE_AUTH_KEY }}
      APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
      APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
