name: Build And Deploy iOS

on:
  workflow_call:
    inputs:
      unity_version:
        description: "Unity version used for the build"
        required: true
        type: string

      artifact_name:
        description: "Name of the artifact containing the Unity build"
        required: true
        type: string

    secrets:
      APPLE_DISTRIBUTION_CERTIFICATE:
        description: "Base64-encoded Apple Distribution Certificate (.p12)"
        required: true

      APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD:
        description: "Password for the Apple Distribution Certificate"
        required: true

      DISTRIBUTION_PROVISIONING_PROFILE:
        description: "Base64-encoded Provisioning Profile (.mobileprovision)"
        required: true

      KEYCHAIN_NAME:
        description: "Name of the keychain where the Certificate will be imported"
        required: true

      KEYCHAIN_PASSWORD:
        description: "Password for the keychain where the Certificate will be imported"
        required: true

      APP_STORE_AUTH_KEY:
        description: "Base64-Encoded App Store Auth Key (.p8)"
        required: true

      APP_STORE_ISSUER_ID:
        description: "App Store Auth Key Issuer ID"
        required: true

      APP_STORE_KEY_ID:
        description: "App Store Auth Key ID"
        required: true

jobs:
  build:
    name: Xcode iOS ${{ inputs.unity_version }}
    runs-on: macos-latest

    steps:
      - name: Download Unity iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./iOS-Xcodeproj

      - name: Download certificate, provisioning profile, and App Store Auth Key
        env:
          APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
          APPLE_DISTRIBUTION_CERTIFICATE_PATH: ${{ runner.temp }}/AppleDistributionCertificate.p12
          DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.DISTRIBUTION_PROVISIONING_PROFILE }}
          DISTRIBUTION_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/DistributionProvisioningProfile.mobileprovision
          APP_STORE_AUTH_KEY: ${{ secrets.APP_STORE_AUTH_KEY }}
          APP_STORE_AUTH_KEY_PATH: ${{ runner.temp }}/AppStoreAuthKey.p8
        run: |
          if ! printf "%s" "$APPLE_DISTRIBUTION_CERTIFICATE" | base64 --decode -o "$APPLE_DISTRIBUTION_CERTIFICATE_PATH"; then
            echo "Failed to decode Distribution Certificate" >&2
            exit 1
          fi

          if ! printf "%s" "$DISTRIBUTION_PROVISIONING_PROFILE" | base64 --decode -o "$DISTRIBUTION_PROVISIONING_PROFILE_PATH"; then
            echo "Failed to decode Provisioning Profile" >&2
            exit 1
          fi

          if ! printf "%s" "$APP_STORE_AUTH_KEY" | base64 --decode -o "$APP_STORE_AUTH_KEY_PATH"; then
            echo "Failed to decode App Store Auth Key" >&2
            exit 1
          fi

      - name: Build Xcode Project using Fastlane
        env:
          FASTLANE_OUTPUT_NAME: AppleAuth_${{ inputs.unity_version }}.ipa
          APPLE_DISTRIBUTION_CERTIFICATE_PATH: ${{ runner.temp }}/AppleDistributionCertificate.p12
          APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          DISTRIBUTION_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/DistributionProvisioningProfile.mobileprovision
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APP_STORE_AUTH_KEY_PATH: ${{ runner.temp }}/AppStoreAuthKey.p8
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          UNITY_VERSION: ${{ inputs.unity_version }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
            cd ./iOS-Xcodeproj
            fastlane --version
            fastlane env
            fastlane ios build --verbose
        
            echo "Fastlane build finished"
